working with props
NikitaProshyn/FE28ThirdBlock pull request #1
Opened 2022-08-10 21:22 UTC by NikitaProshyn

2022-08-30 15:16 UTC, vl-domorad requested changes

2022-08-30 15:16 UTC, vl-domorad commented on src/App.tsx
> +            }
Это все проверять внутри компонента header, просто в него передать isOpened

2022-08-30 15:16 UTC, vl-domorad commented on src/components/card/Card.tsx
> +const Card = ({ card, size }: any) => {
Протипизировать props

2022-09-27 15:58 UTC, vl-domorad requested changes

2022-09-27 15:58 UTC, vl-domorad commented on src/App.tsx
> +                  />
```
!isOpened && (
                  <Input
                     placeholder={'Placeholder'}
                     onChange={onChange}
                     value={value}
                  />
```

2022-09-27 15:58 UTC, vl-domorad commented on src/Pages/Blog/Components/SinglePostModal/SinglePostModal.tsx
> +import card from '../../../../components/card';
Card с большой буквы

2022-09-27 15:58 UTC, vl-domorad commented on src/components/ModalWindow/ModalWindow.tsx
> +            })}
Исправить, прокидывать просто доп className, а не вытягивать isVisible селекторами, у тебя ModalWindow - dump component

2022-09-27 15:58 UTC, vl-domorad commented on src/components/Post/Post.tsx
> +                        <ThumbsDown />
Количество лайков где?

2022-09-27 15:58 UTC, vl-domorad commented on src/components/header/Header.tsx
> +const Header = ({ onClick, input, isOpened }: any) => {
Протипизировать

2022-09-27 15:58 UTC, vl-domorad commented on src/components/header/Menu/Menu.tsx
> +            </NavLink>
Промапить массив элементов

2022-09-28 16:02 UTC, NikitaProshyn commented on src/Pages/Blog/Components/SinglePostModal/SinglePostModal.tsx
> +import card from '../../../../components/card';
Я знаю 
 Я же писал тебе, что у меня тупо проект ложиться, все остальное же с большой делаю

2022-09-28 16:31 UTC, NikitaProshyn commented on src/App.tsx
> +                  />
Эта ошибка давно пофикшена, что-то странно

2022-09-28 16:32 UTC, NikitaProshyn commented on src/components/Post/Post.tsx
> +                        <ThumbsDown />
Лайки тоже есть

2022-09-28 16:55 UTC, NikitaProshyn commented on src/components/header/Header.tsx
> +const Header = ({ onClick, input, isOpened }: any) => {
Готово

2022-09-28 16:59 UTC, NikitaProshyn commented on src/components/header/Menu/Menu.tsx
> +            </NavLink>
Не понял тут немного

2022-10-01 15:07 UTC, NikitaProshyn commented on src/components/ModalWindow/ModalWindow.tsx
> +            })}
Ready

2022-10-01 16:17 UTC, merged